### ISSUE TITLE
有没升级支持 selenium 4 计划？

### ISSUE THREAD

**Issue by bitlin** [Chras-fu/Liuma-engine#2]
Python库最新版：[selenium 4.1.5](https://pypi.org/project/selenium/4.1.5/)

**Comment by Chras-fu** [comment]
最早我是使用selenium4来进行调试的，后来发现有些操作不太稳定，就改为selenium3。
其实3和4对引擎乃至整个平台影响并不大，我并未对selenium做二次开发，只是将其操作接口翻译为关键字。所以理论上selenium4是兼容的，您可以将引擎的selenium依赖版本直接升级到最新版。
当然selenium4有一些新的操作和特性，您可以自行新增关键字，有两个办法：一是只需要在平台控件管理处自行定义新操作关键字，并按照规范写操作代码。二是参考/core/web/driver下的文件定义新的操作函数，并在find_opt.py文件将这些函数利用解释器关联为关键字，最终将这些关键字参考已有关键字数据进行数据库表operation插入。然后就可以在编写用例时使用。
综上，考虑到稳定性，我暂时仍使用selenium3。但是您可以自行升级至selenium4，其本身就是兼容的。
