### ISSUE TITLE
请问如何启动多个系统引擎，配置文件需要怎么修改

### ISSUE THREAD

**Issue by ishallyz** [Chras-fu/Liuma-engine#4]

**Comment by Chras-fu** [comment]
多个引擎只需要更改引擎code和secret即可，启动步骤重复操作。
参考部署手册：https://docs.qq.com/doc/p/c989fa8bf467eca1a1e0fa59b32ceab017407168

**Comment by dummersoul** [comment]
> 

请问引擎启动时log报错： 调用发送引擎心跳接口 响应状态为：500 ，这种情况如何处理

**Comment by Chras-fu** [comment]
> > 
> 
> 请问引擎启动时log报错： 调用发送引擎心跳接口 响应状态为：500 ，这种情况如何处理

检查下配置文件是否正确，可以去官网社区查看是否有相似问题，若没有可以带上配置文件截图以及具体环境描述进行提问

**Comment by dummersoul** [comment]
我是docker部署的，config.ini 内容如下，不知道是否正确
![image](https://user-images.githubusercontent.com/59673757/212225268-23e78669-944b-4ca4-9d80-31a55fae2682.png)
172.17.0.2:4444/wd/hub 页面显示是否存在问题，或许源头在这里吗
![image](https://user-images.githubusercontent.com/59673757/212225488-e49713e6-54a4-4109-a72e-07375f328f87.png)
